// 1_2024_frontend/implementation/react/src/components/SlideShow.jsx
import { useRef, useMemo } from 'react'
import { TransitionGroup, CSSTransition } from 'react-transition-group'
import './SlideShow.css'

const themeTimeouts = {
  themeA: 0,
  themeB: 800,
  themeC: 2000,
  themeD: 800,
  themeE: 500,
  themeF: 1500,
};

export default function SlideShow({ themeList, currentThemeIndex, imageList, currentImageIndex, slideCount }) {
  const slideWindowRef = useRef(null);

  const currentTheme = themeList[currentThemeIndex].en;
  const slideKey = `${currentImageIndex}-${slideCount}`;
  const timeout = themeTimeouts[currentTheme] || 0;

  // key 変更ごとに新しい ref を生成
  // TransitionGroup は前回レンダーの要素を内部 state に保持し、exit 時にそれを clone する。
  // そのため exit 中の CSSTransition は前回レンダー時の ref オブジェクトをそのまま持ち、
  // .current が旧 DOM ノードを指し続けるので exit アニメーションは正常に動作する。
  const nodeRef = useMemo(() => ({ current: null }), [slideKey]);

  // --r のランダム値をスライドごとに1回だけ生成
  const randomR = useMemo(() => Math.floor(Math.random() * 11), [slideKey]);

  function slideShowFullScreen() {
    if (!document.fullscreenElement) {
      slideWindowRef.current?.requestFullscreen();
    } else {
      document.exitFullscreen?.();
    }
  }

  const currentImage = imageList[currentImageIndex];
  const isThemeE = currentTheme === 'themeE';

  return (
    <div className={`slide-show ${currentTheme}-slide-show`}>
      <h1>スライドショー</h1>
      <div className="slide-window" ref={slideWindowRef}>
        <TransitionGroup component={null}>
          <CSSTransition
            key={slideKey}
            classNames={currentTheme}
            timeout={timeout}
            nodeRef={nodeRef}
          >
            {isThemeE ? (
              <div className="slide" ref={nodeRef}>
                <img className="left" src={currentImage?.base64} alt={currentImage?.name} />
                <img className="right" src={currentImage?.base64} alt={currentImage?.name} />
              </div>
            ) : (
              <figure className="slide" ref={nodeRef} style={{ '--r': randomR }}>
                <img src={currentImage?.base64} alt={currentImage?.name} />
                <figcaption>
                  {currentImage?.name ? (
                    currentImage.name.split(' ').map((word, index) => (
                      <span key={`${word}-${index}`} style={{ '--i': index + 1 }}>{word} </span>
                    ))
                  ) : (
                    '画像が設定されていません'
                  )}
                </figcaption>
              </figure>
            )}
          </CSSTransition>
        </TransitionGroup>
      </div>
      <button onClick={slideShowFullScreen}>フルスクリーン表示</button>
    </div>
  )
}

// 1_2024_frontend/dev-vue/implementation/src/components/SlideShow.vue
<script lang="js">
export default {
  name: "SlideShow",
  components: {

  },
  emits: [],
  inject: [
    "themeList",
    "currentThemeIndex",
    "imageList",
    "curenntImageIndex",
    "slideCount",
  ],
  data() {
    return {

    }
  },
  computed: {

  },
  async created() {

  },
  mounted() {

  },
  beforeUnmount() {

  },
  watch: {

  },
  methods: {
    slideShowFullScreen() {
      if (!document.fullscreenElement) {
        this.$refs["slide-window"].requestFullscreen();
      } else {
        document.exitFullscreen?.();
      }
    },

  },
}
</script>

<template>
  <div class="slide-show" :class="`${themeList[currentThemeIndex].en}-slide-show`">
    <h1>スライドショー</h1>
    <div class="slide-window" ref="slide-window">
      <Transition :name="`${themeList[currentThemeIndex].en}`">

        <template v-if="themeList[currentThemeIndex].en !== 'themeE'">
          <figure class="slide" :key="`${curenntImageIndex}-${slideCount}`"
            :style="`--r:${Math.floor(Math.random() * 10)};`">

            <img :src="imageList[curenntImageIndex]?.base64" :alt="imageList[curenntImageIndex]?.name">

            <figcaption>

              <template v-if="imageList[curenntImageIndex]?.name">
                <span v-for="(word, index) in imageList[curenntImageIndex]?.name.split(' ')" :key="`${word}-${index}`"
                  :style="`--i:${index + 1}`">
                  <template v-if="index !== 0">&nbsp;</template>{{ word }}
                </span>
              </template>

              <template v-else>
                画像が設定されていません
              </template>

            </figcaption>
          </figure>
        </template>

        <template v-else>
          <div class="slide" :key="`${curenntImageIndex}-${slideCount}`">
            <img class="left" :src="imageList[curenntImageIndex]?.base64" :alt="imageList[curenntImageIndex]?.name">
            <img class="right" :src="imageList[curenntImageIndex]?.base64" :alt="imageList[curenntImageIndex]?.name">
          </div>
        </template>

      </Transition>
    </div>
    <div><button @click="slideShowFullScreen">フルスクリーン表示</button></div>
  </div>
</template>

<style scoped>
.slide-show {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.slide-window {
  width: 100%;
  height: 320px;
  border: 1px solid #acacac;
  background: #efefef;
  overflow: hidden;
  position: relative;
}

.slide {
  width: 100%;
  height: 100%;
  position: absolute;
}

.slide img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  position: absolute;
  z-index: 500;
}

.slide figcaption {
  position: absolute;
  background: #fff;
  bottom: 0;
  left: 0;
  padding: 8px;
  border-radius: 0 8px 0 0;
  z-index: 600;
}

.slide figcaption span {
  display: inline-block;
}
</style>
