// 5_2024_mobile-app/implementation/react/src/views/SettingsView.jsx
import { useEffect } from "react";
import { useAppContext } from "../AppContext";
import styles from "./SettingsView.module.css";

export default function SettingsView() {
  const { setHeaderH1, themeMode, setThemeMode, sortMode, setSortMode } = useAppContext();

  useEffect(() => {
    setHeaderH1("Setting");
  }, []);

  return (
    <div className={styles.settingsView}>
      <p><label>theme : <select value={themeMode} onChange={(e) => setThemeMode(Number(e.target.value))}>
        <option value={0}>dark theme</option>
        <option value={1}>light theme</option>
        <option value={2}>option to follow the system's</option>
      </select></label></p>
      <p><label>Carpark Sorting method : <select value={sortMode} onChange={(e) => setSortMode(Number(e.target.value))}>
        <option value={0}>alphabet</option>
        <option value={1}>distance between the current location to each carpark</option>
      </select></label></p>
    </div>
  );
}

// 5_2024_mobile-app/implementation/vue/src/views/SettingsView.vue
<script setup>
import { inject } from "vue";

const headerH1 = inject("headerH1")
const themeMode = inject("themeMode")
const sortMode = inject("sortMode")

headerH1.value = "Setting"
</script>

<template>
  <div class="settings-view">
    <p><label>theme : <select name="themeMode" id="themeMode" v-model.number="themeMode">
      <option value="0">dark theme</option>
      <option value="1">light theme</option>
      <option value="2">option to follow the system's</option>
    </select></label></p>
    <p><label>Carpark Sorting method : <select name="sortMode" id="sortMode" v-model.number="sortMode">
      <option value="0">alphabet</option>
      <option value="1">distance between the current location to each carpark</option>
    </select></label></p>
  </div>
</template>

<style scoped>
.settings-view {
  padding: 24px;
  display: flex;
  flex-direction: column;
  align-items: start;
  gap: 24px;
  height: 100%;
  overflow-y: auto;
}

.settings-view>* {
  display: flex;
  flex-direction: column;
  align-items: start;
  gap: 24px;
}

.settings-view>*>* {
  display: flex;
  flex-direction: column;
  align-items: start;
  gap: 8px;
}
</style>
